spring:
  application:
    name: speedrun

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ecommerce
    username: sa
    password:

  sql:
    init:
      mode: always
      data-locations: classpath:products.sql, classpath:clients.sql

  h2:
    console:
      enabled: true           # Habilita la consola web de H2
      path: /h2-console      # Ruta para acceder a la consola (http://localhost:8080/h2-console)
  jpa:
    defer-datasource-initialization: true